/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lib.Server;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Arden
 */
public class ServerFrame extends javax.swing.JFrame {

    /**
     * Creates new form ServerFrame
     */
    
    public SocketServer server;
    public Thread serverThread;
    public String filePath = "D:/Data.xml";
    public JFileChooser fileChooser;
    
    public ServerFrame() {
	initComponents();
	jtfFileDatabase.setEditable(false);
	
	fileChooser = new JFileChooser();
	jtaProses.setEditable(false);
    }
    
    public boolean isWindows () {
	return System.getProperty("os.name").startsWith("Windows");
    }
    
    public void RetryStart (int port) {
	if (server != null)
	    server.stop();
	server = new SocketServer(this, port);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbFileDatabase = new javax.swing.JLabel();
        jtfFileDatabase = new javax.swing.JTextField();
        jbtBrowse = new javax.swing.JButton();
        jbtStart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaProses = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbFileDatabase.setText("File Database :");
        jlbFileDatabase.setName("jlbFileDatabase"); // NOI18N

        jtfFileDatabase.setName("jtfFileDatabase"); // NOI18N

        jbtBrowse.setText("Cari...");
        jbtBrowse.setName("jbtBrowseFile"); // NOI18N
        jbtBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBrowseActionPerformed(evt);
            }
        });

        jbtStart.setText("Mulai Server");
        jbtStart.setEnabled(false);
        jbtStart.setName("jbtStartServer"); // NOI18N
        jbtStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtStartActionPerformed(evt);
            }
        });

        jtaProses.setEditable(false);
        jtaProses.setColumns(20);
        jtaProses.setRows(5);
        jtaProses.setName("jtaProses"); // NOI18N
        jScrollPane1.setViewportView(jtaProses);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbFileDatabase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfFileDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtBrowse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtStart)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbFileDatabase)
                    .addComponent(jtfFileDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtBrowse)
                    .addComponent(jbtStart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBrowseActionPerformed
        fileChooser.showDialog(this, "Pilih");
	File file = fileChooser.getSelectedFile();
	
	if (file != null) {
	    filePath = file.getPath();
	    if (this.isWindows()) {
		filePath = filePath.replace("\\", "/");
	    }
	    jtfFileDatabase.setText(filePath);
	    jbtStart.setEnabled(true);
	}
    }//GEN-LAST:event_jbtBrowseActionPerformed

    private void jbtStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtStartActionPerformed
        server = new SocketServer(this);
	jbtBrowse.setEnabled(false);
	jbtStart.setEnabled(false);
    }//GEN-LAST:event_jbtStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Windows".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
	    System.out.println("Look & Feel Exception");
	}
        //</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new ServerFrame().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtBrowse;
    private javax.swing.JButton jbtStart;
    private javax.swing.JLabel jlbFileDatabase;
    public javax.swing.JTextArea jtaProses;
    private javax.swing.JTextField jtfFileDatabase;
    // End of variables declaration//GEN-END:variables
}
