/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lib.Client;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import lib.Message;

/**
 *
 * @author Arden
 */
public class ChatFrame extends javax.swing.JFrame {
    
    public SocketClient client;
    public int port;
    public String serverAddr, username, password;
    public Thread clientThread;
    public DefaultListModel model;
    public File file;
    public String historyFile = "D:/History.xml";
    public HistoryFrame historyFrame;
    public History history;
    
    public ChatFrame() {
	initComponents();
	this.setTitle("jMessenger");
	model.addElement("All");
	jlistUserOnline.setSelectedIndex(0);
	
	this.addWindowListener(new WindowAdapter() {
	    public void windowClosing(WindowEvent e) {
		try {
		    client.send(new Message("message", username, ".bye", "SERVER"));
		}
		catch (Exception ex) {}
	    }
	});
	history = new History(historyFile);
    }
    
    public boolean isWindows() {
	return System.getProperty("os.name").startsWith("Windows");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfHostAddr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfHostPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jpfPassword = new javax.swing.JPasswordField();
        jbtConnect = new javax.swing.JButton();
        jbtLogin = new javax.swing.JButton();
        jbtSignUp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistUserOnline = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaMessage = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jbtSendMessage = new javax.swing.JButton();
        jbtBrowseFile = new javax.swing.JButton();
        jbtSendFile = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfFile = new javax.swing.JTextField();
        jtfMessage = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Host Address :");

        jtfHostAddr.setText("localhost");

        jLabel2.setText("Host Port :");

        jtfHostPort.setText("13000");

        jLabel3.setText("Username :");

        jtfUserName.setText("Arden");

        jLabel4.setText("Password :");

        jpfPassword.setText("--------");

        jbtConnect.setText("Connect");
        jbtConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConnectActionPerformed(evt);
            }
        });

        jbtLogin.setText("Login");
        jbtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLoginActionPerformed(evt);
            }
        });

        jbtSignUp.setText("SignUp");
        jbtSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSignUpActionPerformed(evt);
            }
        });

        jlistUserOnline.setModel(model = new DefaultListModel());
        jScrollPane1.setViewportView(jlistUserOnline);

        jtaMessage.setColumns(20);
        jtaMessage.setRows(5);
        jScrollPane2.setViewportView(jtaMessage);

        jLabel5.setText("Message :");

        jbtSendMessage.setText("Send Message");

        jbtBrowseFile.setText("...");
        jbtBrowseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBrowseFileActionPerformed(evt);
            }
        });

        jbtSendFile.setText("Send");
        jbtSendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSendFileActionPerformed(evt);
            }
        });

        jLabel6.setText("File :");

        jtfMessage.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfHostAddr, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jtfUserName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfHostPort)
                            .addComponent(jpfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfMessage)
                                    .addComponent(jtfFile)))
                            .addComponent(jScrollPane2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtBrowseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtSendFile, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtSendMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfHostAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jtfHostPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtConnect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtLogin)
                            .addComponent(jbtSignUp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jtfMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtSendMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jbtBrowseFile)
                    .addComponent(jbtSendFile))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConnectActionPerformed
        serverAddr = jtfHostAddr.getText();
	port = Integer.parseInt(jtfHostPort.getText());
	
	if (!serverAddr.isEmpty() && !jtfHostPort.getText().isEmpty()) {
	    try {
		client = new SocketClient(this);
		clientThread = new Thread(client);
		clientThread.start();
		client.send(new Message("test", "testUser", "testContent", "SERVER"));
	    }
	    catch (IOException e) {
		jtaMessage.append("[Aplikasi > Me] : Server tidak ditemukan\n");
	    }
	}
    }//GEN-LAST:event_jbtConnectActionPerformed

    private void jbtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLoginActionPerformed
        String msg = jtfMessage.getText();
	String target = jlistUserOnline.getSelectedValue().toString();
	
	if (!msg.isEmpty() && !target.isEmpty()) {
	    jtfMessage.setText("");
	    client.send(new Message("message", username, msg, target));
	}
    }//GEN-LAST:event_jbtLoginActionPerformed

    private void jbtSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSignUpActionPerformed
        username = jtfUserName.getText();
	password = jpfPassword.getText();
	
	if (!username.isEmpty() && !password.isEmpty()) {
	    client.send(new Message("signup", username, password, "SERVER"));
	}
    }//GEN-LAST:event_jbtSignUpActionPerformed

    private void jbtBrowseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBrowseFileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
	fileChooser.showDialog(this, "Select File");
	file = fileChooser.getSelectedFile();
	
	if (file != null) {
	    if (!fileChooser.getName().isEmpty()) {
		jbtSendFile.setEnabled(true);
		String str;
		if (jtfFile.getText().length() > 30) {
		    String t = file.getPath();
		    str = t.substring(0, 20) + " [...] " + t.substring(t.length() - 20, t.length());
		}
		else {
		    str = file.getPath();
		}
		jtfFile.setText(str);
	    }
	}
    }//GEN-LAST:event_jbtBrowseFileActionPerformed

    private void jbtSendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSendFileActionPerformed
        long size = file.length();
	if (size < 120 * 1024 * 1024) {
	    client.send(new Message("upload_req", username, file.getName(), jlistUserOnline.getSelectedValue().toString()));
	}
	else {
	    jtaMessage.append ("[Aplikasi > Me] : File kebesaran Max 120MB\n");
	}
    }//GEN-LAST:event_jbtSendFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
        //</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new ChatFrame().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JButton jbtBrowseFile;
    public javax.swing.JButton jbtConnect;
    public javax.swing.JButton jbtLogin;
    public javax.swing.JButton jbtSendFile;
    public javax.swing.JButton jbtSendMessage;
    public javax.swing.JButton jbtSignUp;
    public javax.swing.JList jlistUserOnline;
    public javax.swing.JPasswordField jpfPassword;
    public javax.swing.JTextArea jtaMessage;
    public javax.swing.JTextField jtfFile;
    public javax.swing.JTextField jtfHostAddr;
    public javax.swing.JTextField jtfHostPort;
    private javax.swing.JTextField jtfMessage;
    public javax.swing.JTextField jtfUserName;
    // End of variables declaration//GEN-END:variables
}
